pipeline {
    agent any

     environment {
            GIT_COMMIT_HASH = sh (script: "git log --pretty=format:'%h' -n 1", returnStdout: true)
        }

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven 'maven'
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                    sed -i "s/GIT_COMMIT_ID/$GIT_COMMIT_HASH/g" application/src/main/java/vn/com/viettel/his/controller/HomeController.java
                    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
                    rm -rf ./target

                    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar \
                                            -Dsonar.host.url=http://10.60.98.80:8003 \
                                            -Dsonar.login=cb001dcc5e17eeed6142d86ea1bdc43eea312adc  --settings /var/lib/jenkins/.m2/his_settings.xml

                    mvn clean install --settings /var/lib/jenkins/.m2/his_settings.xml -DskipTests
                    mv ./application/target/*-SNAPSHOT.jar ./application/target/app.jar
                '''
            }
        }

        stage('Deploy Docker') {
	        steps {
               sh '''
                    eval `ssh-agent -s`
                    ssh-add ~/.ssh/phanphoi
                    scp -P 8308 -o StrictHostKeyChecking=no ./application/target/app.jar root@10.60.98.80:/home/vss.deploy/HIS/backend/test/greeting/
                    scp -P 8308 -o StrictHostKeyChecking=no ./docker/Dockerfile root@10.60.98.80:/home/vss.deploy/HIS/backend/test/greeting/
                    ssh -p 8308 -o StrictHostKeyChecking=no root@10.60.98.80 "/home/vss.deploy/HIS/backend/test/greeting/run.sh"
               '''
            }
        }
    }
}
